# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  DeployToAzure:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: azureforumsecretmanagement
      ResourceGroupLocation: "northeurope"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Bicep Build
        run: |
          az bicep build --file infra/v1/main.bicep
      - name: Create Resource Group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
      - name: deploy infrastructure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.ResourceGroupName }}
          template: ./infra/v1/main.json
          failOnStdErr: false
